services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"       
      - "127.0.0.1:4510-4559:4510-4559" 
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DYNAMODB_SHARE_DB=1
    volumes:
      - ./localstack-scripts:/etc/localstack/init/ready.d
      - "/var/run/docker.sock:/var/run/docker.sock"